apiVersion: v1
kind: Secret
metadata:
  name: app-book-secrets
type: Opaque
data:
  PGUSER: <base64 user>
  PGPASSWORD: <base64 password>
  PGDATABASE: <base 64 database>
  ECR_REPOSITORY: <base 64 AWS ECR repo>

  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-book-secrets
data:
  PGHOST: postgres-service
  PGPORT: "5432"
