apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
              valueFrom:
                configMapKeyRef:
                  name: app-book-configmap
                  key: PGPORT
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGDATABASE
              #value: "{{ .Values.env.POSTGRES_DB }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGUSER
              #value: "{{ .Values.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGPASSWORD           
              #value: "{{ .Values.env.POSTGRES_PASSWORD }}"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}