apiVersion: v1
kind: Service
metadata:
  name: app-book
  namespace: {{ .Values.namespace }}
  labels:
    app: app-book
spec:
  selector:
    app: app-book  # The selector, it uses the service to know which pod to send the traffic to
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.port }} # This is the service port (what clients use to talk to the service)
      targetPort: {{ .Values.service.targetPort }} # This is the container port (the port inside your pod/app)
