apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-book
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-book #  This binds the Deployment to its Pods
  template:
    metadata:
      labels:
        app: app-book # This label MUST match the Service selector
    spec:
      imagePullSecrets:
        - name: ecr-registry-credentials
      containers:
        - name: app-book
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            #- containerPort: {{ .Values.container.targetPort }}
            - name: metrics  # This must match the PodMonitor "port" field
              containerPort: {{ .Values.container.targetPort }}
          env:
            - name: PGHOST
              value: {{ .Values.env.PGHOST }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGPASSWORD          
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: app-book-configmap
                  key: PGPORT              
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-book-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGUSER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-book-secrets
                  key: PGPASSWORD 
              
