apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-book
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-book #  This binds the Deployment to its Pods
  template:
    metadata:
      labels:
        app: app-book # This label MUST match the Service selector
    spec:
      imagePullSecrets:
        - name: ecr-registry-credentials
      containers:
        - name: app-book
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            #- containerPort: {{ .Values.container.targetPort }}
            - name: metrics  # This must match the PodMonitor "port" field
              containerPort: 8080
          env:
            - name: PGHOST
              value: {{ .Values.env.PGHOST }}
            - name: PGUSER
              value: {{ .Values.env.PGUSER }}
            - name: PGPASSWORD
              value: "{{ .Values.env.PGPASSWORD }}"
            - name: PGDATABASE
              value: {{ .Values.env.PGDATABASE }}
            - name: PGPORT
              value: "5432"
              
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/john_duran_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
              
