namespace: app-book

replicaCount: 1

image:
  repository: 948586925757.dkr.ecr.us-east-1.amazonaws.com/app-book
  tag: "1.0.2"
  pullPolicy: always

container:
  targetPort: "8080"

service:
  port: "8080"
  targetPort: "8080"

env:
  PGHOST: postgres-service
  PGUSER: postgres
  PGPASSWORD: "postgres"
  PGDATABASE: john_duran_db
  PGPORT: "5432"
  